name = "BEMT"
uuid = "43670391-414f-4d66-8710-74f833c64013"
authors = ["Guilain Ernotte <guilainsjc@gmail.com>"]
version = "1.0.0-DEV"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
julia = "1"
